// player actions
export const SET_CURRENT_FILE = 'SET_CURRENT_FILE'
export const TOGGLE_RANDOM = 'TOGGLE_RANDOM'
export const TOGGLE_REPEAT = 'TOGGLE_OPTIONS'
export const TOGGLE_PLAYING = 'TOGGLE_PLAYING'
export const SET_FILES_ARRAY = 'SET_FILES_ARRAY'
export const CLEAR_FILES_ARRAY = 'CLEAR_FILES_ARRAY'
export const EDIT_FILE = 'EDIT_FILE'
export const EDIT_FILES = 'EDIT_FILES'
export const MOVE_FILES = 'MOVE_FILES'
export const REMOVE_FILE = 'REMOVE_FILE'
export const REMOVE_FILES = 'REMOVE_FILES'
